package com.foggy.navigator.common.authorization.preseed;

/**
 * Stable, public-safe reasons for offline pre-seed inventory validation.
 * Values intentionally contain no input, credential, token, or profile data.
 */
public enum PreseedInventoryReasonCode {
    PRESEED_VALID,
    PRESEED_DOCUMENT_MALFORMED,
    PRESEED_SCHEMA_UNSUPPORTED,
    PRESEED_MODE_UNSUPPORTED,
    PRESEED_DEPLOYMENT_MISSING,
    PRESEED_RECORDS_MISSING,
    PRESEED_UNSUPPORTED_FIELD,
    PRESEED_SECRET_LIKE_INPUT,
    PRESEED_CHECKSUM_MISMATCH,
    PRESEED_RECORD_INVALID,
    PRESEED_SOURCE_MAPPING_MISSING,
    PRESEED_SOURCE_MAPPING_AMBIGUOUS,
    PRESEED_SOURCE_MAPPING_CONFLICT,
    PRESEED_OWNER_CONFLICT,
    PRESEED_CLIENT_APP_CONFLICT,
    PRESEED_AUTHORITY_FACTS_MISSING,
    PRESEED_CREDENTIAL_REVOKED,
    PRESEED_CREDENTIAL_EXPIRED,
    PRESEED_CREDENTIAL_EXPIRY_REQUIRED,
    PRESEED_CREDENTIAL_STATUS_INVALID,
    PRESEED_FINGERPRINT_INVALID,
    PRESEED_TENANT_AUTHORITY_DUPLICATE,
    PRESEED_TENANT_AUTHORITY_CONFLICT,
    PRESEED_LEGACY_REQUIRES_APPROVAL,
    PRESEED_LEGACY_PROMOTION_PROHIBITED,
    PRESEED_DISPOSITION_REQUIRES_APPROVAL,
    PRESEED_RECORD_DECLARED_QUARANTINE
}
