export {
  AipMessageType,
  type AipMessage,
  type TextPayload,
  type ToolCallStartPayload,
  type ToolCallResultPayload,
  type ToolCallErrorPayload,
  type ThinkingPayload,
  type StateSyncPayload,
  type ErrorPayload,
  type TaskCompletedPayload,
  type ConfirmationRequestPayload,
  type UserQuestionItem,
  type UserQuestionOption,
} from '@foggy/chat-core'
