package com.foggy.navigator.business.agent.model.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * Durable fail-closed tombstone for a terminal provider task.
 *
 * <p>The provider task identifier is generated by Navigator and is only unique
 * inside a tenant boundary. If a definitive terminal event wins the race with
 * token binding, an unbound marker is stored with null capability correlation.
 * The provider-task owner is retained separately because it is not necessarily
 * the same principal as the capability actor (for example, an OpenAPI task may
 * execute as an Agent owner while its task token acts as a ClientApp). Only an
 * exact tenant + workerTask token binding may enrich businessTaskId and
 * navigatorEffectiveUserId; request-carried correlation is never used.</p>
 *
 * <p>Expired rows stop participating in authorization checks but are currently
 * retained. Physical cleanup is an explicit follow-up rather than an implicit
 * side effect of terminal event processing.</p>
 */
@Data
@Entity
@Table(name = "business_task_terminal_state",
        uniqueConstraints = {
                @UniqueConstraint(name = "uk_biz_terminal_tenant_worker_task",
                        columnNames = {"tenantId", "workerTaskId"})
        },
        indexes = {
                @Index(name = "idx_biz_terminal_tenant_business_task",
                        columnList = "tenantId,businessTaskId"),
                @Index(name = "idx_biz_terminal_expires_at", columnList = "expiresAt")
        })
public class BusinessTaskTerminalStateEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(length = 64, nullable = false)
    private String tenantId;

    @Column(length = 128, nullable = false)
    private String workerTaskId;

    @Column(length = 64)
    private String businessTaskId;

    @Column(length = 64)
    /** Event source Agent ID; it is not guaranteed to be a Provider type. */
    private String sourceAgentId;

    /** Owner copied from the persisted provider task, never a capability actor. */
    @Column(length = 64, nullable = false)
    private String providerTaskUserId;

    /** Capability actor derived only from an exact persisted token binding. */
    @Column(length = 64)
    private String navigatorEffectiveUserId;

    @Column(length = 32, nullable = false)
    private String terminalStatus;

    @Column(nullable = false)
    private LocalDateTime terminalAt;

    /**
     * Authorization stops consulting this tombstone only after every task
     * capability that could have observed the terminal event has expired.
     */
    @Column(nullable = false)
    private LocalDateTime expiresAt;

    private LocalDateTime revocationCompletedAt;

    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(nullable = false)
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = createdAt;
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
