package com.foggy.navigator.common.authorization;

/**
 * Stable, public-safe canonical reasons. Values deliberately contain no raw
 * credential, account, tenant, target, request-body, or token material.
 */
public enum AuthorizationReasonCode {
    AUTHN_CREDENTIAL_MISSING,
    AUTHN_CREDENTIAL_CONFLICT,
    AUTHN_CREDENTIAL_INVALID,
    AUTHN_CREDENTIAL_EXPIRED,
    AUTHN_CREDENTIAL_REVOKED,
    AUTHN_CREDENTIAL_GENERATION_MISMATCH,
    AUTHZ_ENVIRONMENT_MISMATCH,
    AUTHZ_INSTANCE_MISMATCH,
    AUTHZ_PRINCIPAL_TYPE_DENIED,
    AUTHZ_CREDENTIAL_LANE_DENIED,
    AUTHZ_ACTION_DENIED,
    AUTHZ_ACTION_TOKEN_MISMATCH,
    AUTHZ_ACTION_TOKEN_REPLAYED,
    AUTHZ_STEP_UP_REQUIRED,
    AUTHZ_APPROVAL_REQUIRED,
    AUTHZ_SCHEMA_UNSUPPORTED,
    AUTHZ_POLICY_VERSION_UNSUPPORTED,
    AUTHZ_CATALOG_VERSION_MISMATCH,
    AUTHZ_REQUIRED_SECTION_MISSING,
    AUTHZ_REQUIRED_SECTION_UNVERIFIED,
    AUTHZ_REQUIRED_SECTION_CONFLICT,
    AUTHZ_REQUIRED_SECTION_UNKNOWN,
    AUTHZ_PRINCIPAL_UNKNOWN,
    AUTHZ_CREDENTIAL_LANE_UNKNOWN,
    AUTHZ_TRUST_PROFILE_UNKNOWN,
    AUTHZ_ACTION_UNREGISTERED,
    AUTHZ_ROUTE_ACTION_MISMATCH,
    AUTHZ_CREDENTIAL_SOURCE_CONFLICT,
    AUTHZ_DEPLOYMENT_IDENTITY_OVERRIDE,
    AUTHZ_LEGACY_PRINCIPAL_UNVERIFIED,
    AUTHZ_LEGACY_CREDENTIAL_UNVERIFIED,
    AUTHZ_LEGACY_TARGET_UNVERIFIED,
    AUTHZ_LEGACY_CAPABILITY_UNVERIFIED,
    AUTHZ_LEGACY_WORKER_ROUTE_UNVERIFIED,
    AUTHZ_POLICY_SHADOW_ALLOW,
    AUTHZ_POLICY_SHADOW_INCOMPLETE,
    AUTHZ_SHADOW_EVALUATION_ERROR
}
