#!/usr/bin/env bash
# Code Server - HTTPS Setup Script (nginx reverse proxy + self-signed cert)
#
# Usage:
#   bash setup-https.sh --http-port 8444 --https-port 8445 \
#                        --internal-port 8544 --data-dir /path/to/data
#
# This script:
#   1. Installs nginx (if not present)
#   2. Generates self-signed certificate (if not present)
#   3. Creates nginx config (HTTP + HTTPS dual-port reverse proxy)
#   4. Enables config and starts/reloads nginx
#
# Designed to run inside WSL or on a remote Linux server.

set -euo pipefail

# ---- Defaults ----
HTTP_PORT=8444
HTTPS_PORT=8445
INTERNAL_PORT=8544
DATA_DIR="$HOME/.local/share/code-server"
CERT_DAYS=3650  # 10 years
FORCE_REGEN=false
NGINX_CONF_NAME="code-server"

# ---- Parse args ----
while [[ $# -gt 0 ]]; do
  case $1 in
    --http-port)     HTTP_PORT="$2"; shift 2 ;;
    --https-port)    HTTPS_PORT="$2"; shift 2 ;;
    --internal-port) INTERNAL_PORT="$2"; shift 2 ;;
    --data-dir)      DATA_DIR="$2"; shift 2 ;;
    --cert-days)     CERT_DAYS="$2"; shift 2 ;;
    --force-regen)   FORCE_REGEN=true; shift ;;
    -h|--help)
      echo "Usage: $0 [OPTIONS]"
      echo ""
      echo "Options:"
      echo "  --http-port PORT      HTTP listen port (default: 8444)"
      echo "  --https-port PORT     HTTPS listen port (default: 8445)"
      echo "  --internal-port PORT  code-server internal port (default: 8544)"
      echo "  --data-dir DIR        Data directory for certs (default: ~/.local/share/code-server)"
      echo "  --cert-days DAYS      Certificate validity in days (default: 3650)"
      echo "  --force-regen         Force regenerate certificate"
      exit 0
      ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

CERT_DIR="$DATA_DIR/certs"

echo "=== Code Server HTTPS Setup ==="
echo "HTTP port:     $HTTP_PORT"
echo "HTTPS port:    $HTTPS_PORT"
echo "Internal port: $INTERNAL_PORT"
echo "Cert dir:      $CERT_DIR"
echo ""

# ============================================================
# Step 1: Install nginx (if not present)
# ============================================================
if ! command -v nginx &> /dev/null; then
  echo "[1/3] Installing nginx..."
  if command -v apt-get &> /dev/null; then
    sudo apt-get update -qq
    sudo apt-get install -y -qq nginx
  elif command -v yum &> /dev/null; then
    sudo yum install -y -q nginx
  elif command -v dnf &> /dev/null; then
    sudo dnf install -y -q nginx
  else
    echo "ERROR: No supported package manager found. Install nginx manually."
    exit 1
  fi
  echo "  nginx installed."
else
  echo "[1/3] nginx already installed: $(nginx -v 2>&1)"
fi

# ============================================================
# Step 2: Generate self-signed certificate (if not present)
# ============================================================
echo "[2/3] Checking certificate..."
mkdir -p "$CERT_DIR"

CERT_FILE="$CERT_DIR/cert.pem"
KEY_FILE="$CERT_DIR/key.pem"

if [ -f "$CERT_FILE" ] && [ -f "$KEY_FILE" ] && [ "$FORCE_REGEN" = false ]; then
  # Check expiry
  EXPIRY=$(openssl x509 -enddate -noout -in "$CERT_FILE" 2>/dev/null | cut -d= -f2 || echo "")
  echo "  Certificate exists (expires: ${EXPIRY:-unknown})"
  echo "  Use --force-regen to regenerate."
else
  echo "  Generating self-signed certificate (valid for $CERT_DAYS days)..."

  # Get hostname for the certificate
  HOSTNAME=$(hostname 2>/dev/null || echo "localhost")

  openssl req -x509 -nodes -newkey rsa:2048 \
    -days "$CERT_DAYS" \
    -keyout "$KEY_FILE" \
    -out "$CERT_FILE" \
    -subj "/CN=$HOSTNAME" \
    -addext "subjectAltName=DNS:$HOSTNAME,DNS:localhost,IP:127.0.0.1" \
    2>/dev/null

  chmod 600 "$KEY_FILE"
  chmod 644 "$CERT_FILE"
  echo "  Certificate generated:"
  echo "    cert: $CERT_FILE"
  echo "    key:  $KEY_FILE"
fi

# ============================================================
# Step 3: Generate nginx config + enable + reload
# ============================================================
echo "[3/3] Configuring nginx..."

NGINX_CONF="/etc/nginx/sites-available/$NGINX_CONF_NAME"
NGINX_ENABLED="/etc/nginx/sites-enabled/$NGINX_CONF_NAME"

# Check if sites-available/sites-enabled pattern is supported
if [ -d "/etc/nginx/sites-available" ]; then
  NGINX_STYLE="sites"
elif [ -d "/etc/nginx/conf.d" ]; then
  NGINX_STYLE="conf.d"
  NGINX_CONF="/etc/nginx/conf.d/${NGINX_CONF_NAME}.conf"
  NGINX_ENABLED=""  # conf.d auto-loads .conf files
else
  echo "ERROR: Cannot determine nginx config directory."
  exit 1
fi

# Generate config
sudo tee "$NGINX_CONF" > /dev/null << NGINX_EOF
# Auto-generated by setup-https.sh — do not edit manually
# code-server reverse proxy: HTTP ($HTTP_PORT) + HTTPS ($HTTPS_PORT) → internal ($INTERNAL_PORT)

upstream code_server_backend {
    server 127.0.0.1:$INTERNAL_PORT;
}

# HTTP
server {
    listen $HTTP_PORT;
    server_name _;

    location / {
        proxy_pass http://code_server_backend;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Accept-Encoding gzip;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}

# HTTPS
server {
    listen $HTTPS_PORT ssl;
    server_name _;

    ssl_certificate     $CERT_FILE;
    ssl_certificate_key $KEY_FILE;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://code_server_backend;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Accept-Encoding gzip;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
NGINX_EOF

echo "  Config written to $NGINX_CONF"

# Enable (symlink) if using sites-available pattern
if [ "$NGINX_STYLE" = "sites" ]; then
  # Remove default site if it conflicts on port 80 (leave it alone otherwise)
  sudo ln -sf "$NGINX_CONF" "$NGINX_ENABLED"
  echo "  Enabled: $NGINX_ENABLED"
fi

# Test config
echo "  Testing nginx config..."
if sudo nginx -t 2>&1; then
  echo "  Config test passed."
else
  echo "  ERROR: nginx config test failed!"
  exit 1
fi

# Start or reload nginx
if pgrep -x nginx > /dev/null 2>&1; then
  echo "  Reloading nginx..."
  sudo nginx -s reload
else
  echo "  Starting nginx..."
  sudo nginx
fi

echo ""
echo "=== HTTPS Setup Complete ==="
echo ""
echo "Access URLs:"
echo "  HTTP:  http://localhost:$HTTP_PORT"
echo "  HTTPS: https://localhost:$HTTPS_PORT"
echo ""
echo "Certificate location:"
echo "  cert: $CERT_FILE"
echo "  key:  $KEY_FILE"
echo ""
echo "NOTE: Browser will show a security warning for self-signed cert — this is normal."
echo "      Click 'Advanced' → 'Proceed' to continue."
