import assert from 'node:assert/strict'
import fs from 'node:fs'
import test from 'node:test'

test('operations scripts use isolated paths, port 3062, hidden start, and shutdown grace budget', () => {
  const startPs = fs.readFileSync('start.ps1', 'utf8')
  const stopPs = fs.readFileSync('stop.ps1', 'utf8')
  const startSh = fs.readFileSync('start.sh', 'utf8')
  const stopSh = fs.readFileSync('stop.sh', 'utf8')
  const updatePs = fs.readFileSync('update.ps1', 'utf8')
  const updateSh = fs.readFileSync('update.sh', 'utf8')
  assert.match(startPs, /WindowStyle Hidden/)
  assert.match(startPs, /logs\\run/)
  assert.match(startPs, /3062/)
  assert.match(startSh, /logs\/run/)
  assert.match(startSh, /3062/)
  assert.match(stopPs, /CODEX_APP_SERVER_SHUTDOWN_TIMEOUT_MS/)
  assert.match(stopPs, /ShutdownTimeoutMs \+ 5000/)
  assert.match(stopSh, /shutdown_timeout_ms \+ 5000/)
  assert.match(startPs, /CODEX_APP_SERVER_RUN_DIR/)
  assert.match(startSh, /CODEX_APP_SERVER_RUN_DIR/)
  assert.match(startPs, /CODEX_APP_SERVER_LOG_DIR/)
  assert.match(startSh, /CODEX_APP_SERVER_LOG_DIR/)
  assert.match(startSh, /cd "\$ROOT"/)
  assert.match(startSh, /ready === true/)
  assert.doesNotMatch(stopSh, /\bseq\b/)
  assert.match(startPs, /Invoke-RestMethod/)
  assert.match(startPs, /Health\.ready/)
  assert.match(stopPs, /stop\.request/)
  assert.match(stopSh, /stop\.request/)
  assert.doesNotMatch(stopPs, /Stop-Process -Id \$PidValue\s*$/m)
  assert.match(stopPs, /does not belong/)
  assert.match(stopSh, /does not belong/)
  assert.match(updatePs, /-NoBuild/)
  assert.match(updateSh, /--no-build/)
  assert.doesNotMatch(updatePs, /3052|3061|3162|3262/)
  assert.doesNotMatch(updateSh, /3052|3061|3162|3262/)
})
